version: "3.8"

services:
  my_app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html
    ports:
      - "8003:8000"
      - "5173:5173"
    networks:
      - app-network
    command: sh -c "npm run dev & php-fpm"

networks:
  app-network:
    driver: bridge
