# docker-compose.yml
version: "3.8"

services:
  techfood:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./techfood:/var/www/html # Mount your Laravel project
    command: sh -c "php artisan serve --host=0.0.0.0 --port=8000 & npm run dev"
    networks:
      - app-network
    ports:
      - "8003:8000"
      - "5173:5173"

  # web:
  #   image: nginx:latest
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf
  #     - ./fastcgi-php.conf:/etc/nginx/fastcgi-php.conf
  #     - ./techfood:/var/www/html
  #   ports:
  #     - "8000:80"
  #   networks:
  #     - app-network

  mysql_host:
    image: mariadb:10.5.8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: techfood
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - 33061:3306
    networks:
      - app-network

  # phpmyadmin
  phpmyadmin:
    depends_on:
      - mysql_host
    image: phpmyadmin
    ports:
      - "8010:80"
    environment:
      PMA_HOST: mysql_host
      MYSQL_ROOT_PASSWORD: root
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge
