export const URL = "localhost:8000/";
//export const URL = "rnoep-92-34-244-149.a.free.pinggy.link:8000/";
export const PROTOCOL = "http://";
//export const PROTOCOL = "https://";
export const API_VERSION = "v1/";
export const API = "api/";
export const STORAGE = "storage/";
export const BASE_URL = PROTOCOL + URL;
export const FRONT_END_BASE_URL = "localhost/";
