name: Lint

on: [push, pull_request]

jobs:
  lint:
    name: Run ESLint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # Set to your Node version

      - name: Install dependencies
        run: npm install
        working-directory: ./techfood  # Ensure you're in the correct directory

      - name: Run ESLint
        run: npx eslint .

